name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.test.txt
          pip install git+https://github.com/jazzband/icalevents.git@c368ad8
          pip install git+https://github.com/ics-py/ics-py.git@a0738f1

      - name: Run pytest
        run: |
          pytest --cov=custom_components.ics_calendar tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

